services:
  # Backend Flask API
  - type: web
    name: little-angels-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URI
        value: mongodb+srv://admin:g2wBNDnHZbLHIC0b@littleanglescluster.zuhxodt.mongodb.net/?retryWrites=true&w=majority&appName=LittleAnglesCluster
